export const GAME_STATE_SET_GAMEOVER_WIN = 'GAME_STATE_SET_GAMEOVER_WIN'
export const GAME_STATE_SET_GAMEOVER_LOSE = 'GAME_STATE_SET_GAMEOVER_LOSE'

export const GAME_STATE_RESET = 'GAME_STATE_RESET'
export const GAME_STATE_SET_GUESS  = 'GAME_STATE_SET_GUESS'
